name: Convert Markdown to PDF

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.md'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the workflow with debug logging'
        required: false
        default: false
        type: boolean

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to get all history for proper commit messages

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.1'

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic

      - name: Find modified markdown files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.md

      - name: Convert Markdown to PDF
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.md ]]; then
              echo "Converting $file to PDF"
              # Create directory for the PDF if it doesn't exist
              mkdir -p "$(dirname "${file%.*}.pdf")"
              # Convert markdown to PDF using pandoc with PDF engine
              pandoc "$file" \
                -o "${file%.*}.pdf" \
                --pdf-engine=xelatex \
                -V geometry:margin=1in \
                -V documentclass=article \
                -V colorlinks=true \
                -V linkcolor=blue \
                -V urlcolor=blue \
                --toc
            fi
          done

      - name: Commit PDF files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add **/*.pdf
          git diff --quiet && git diff --staged --quiet || git commit -m "Generate PDFs from markdown files" -a
          git push
