name: Convert README to PDF

on:
  push:
    branches: [ main, master ]
    paths:
      - 'readme.md'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the workflow with debug logging'
        required: false
        default: false
        type: boolean

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic fonts-liberation fonts-dejavu

      - name: Create resume styling
        run: |
          # Create a custom CSS file for modern styling
          cat > modern-style.css << 'EOL'
          body {
            font-family: 'Liberation Sans', Arial, sans-serif;
            line-height: 1.6;
            max-width: 100%;
            margin: 0 auto;
            color: #333;
          }
          h1, h2, h3, h4, h5, h6 {
            font-weight: 600;
            line-height: 1.25;
            margin-top: 1.5em;
            margin-bottom: 0.5em;
            color: #000;
          }
          h1 {
            font-size: 2.2em;
            border-bottom: 1px solid #eee;
            padding-bottom: 0.3em;
          }
          h2 {
            font-size: 1.7em;
            border-bottom: 1px solid #eee;
            padding-bottom: 0.3em;
          }
          h3 {
            font-size: 1.3em;
          }
          a {
            color: #0366d6;
            text-decoration: none;
          }
          code {
            font-family: 'DejaVu Sans Mono', Consolas, monospace;
            background-color: #f6f8fa;
            padding: 0.2em 0.4em;
            border-radius: 3px;
            font-size: 0.9em;
          }
          pre {
            background-color: #f6f8fa;
            border-radius: 3px;
            padding: 16px;
            overflow: auto;
            font-size: 0.9em;
          }
          blockquote {
            padding: 0 1em;
            color: #6a737d;
            border-left: 0.25em solid #dfe2e5;
            margin: 0;
          }
          ul, ol {
            padding-left: 2em;
            margin-bottom: 16px;
            display: block;
          }
          li {
            margin-bottom: 0.5em;
            display: list-item !important;
          }
          li p {
            margin-top: 0.25em;
            margin-bottom: 0.25em;
            display: block !important;
          }
          table {
            border-collapse: collapse;
            width: 100%;
            margin-bottom: 16px;
          }
          table th, table td {
            padding: 6px 13px;
            border: 1px solid #dfe2e5;
          }
          table tr {
            background-color: #fff;
            border-top: 1px solid #c6cbd1;
          }
          table tr:nth-child(2n) {
            background-color: #f6f8fa;
          }
          img {
            max-width: 100%;
          }
          strong {
            font-weight: 600;
          }
          /* Resume specific styles */
          em {
            font-style: italic;
            font-size: 0.9em;
            color: #555;
            display: block;
            margin-bottom: 0.5em;
          }
          EOL

      - name: Create LaTeX template
        run: |
          # Create a simple LaTeX template with better list handling
          cat > custom-template.tex << 'EOL'
          \documentclass[]{article}
          \usepackage{amssymb,amsmath}
          \usepackage{ifxetex,ifluatex}
          \usepackage{fixltx2e}
          \usepackage{enumerate}
          \usepackage[shortlabels]{enumitem}
          \setlist{nosep}
          \setlist[itemize]{leftmargin=*}
          \setlist[enumerate]{leftmargin=*}
          \usepackage{lmodern}
          \usepackage{xcolor}
          \usepackage[setpagesize=false, unicode=false, xetex]{hyperref}
          \hypersetup{breaklinks=true,
                      bookmarks=true,
                      colorlinks=true,
                      urlcolor=blue,
                      linkcolor=blue,
                      pdfborder={0 0 0}}
          \urlstyle{same}
          
          \setmainfont{Liberation Sans}
          \setmonofont{DejaVu Sans Mono}
          
          \begin{document}
          
          $body$
          
          \end{document}
          EOL

      - name: Convert README to PDF
        run: |
          echo "Converting readme.md to PDF"
          
          pandoc readme.md \
            -o readme.pdf \
            --pdf-engine=xelatex \
            -V geometry:margin=1in \
            --template=custom-template.tex \
            --css=modern-style.css \
            --highlight-style=tango
          
          # Debug: Check if PDF was created
          if [ -f "readme.pdf" ]; then
            echo "✅ Successfully created readme.pdf"
            ls -la readme.pdf
          else
            echo "❌ Failed to create readme.pdf"
          fi

      - name: Commit PDF file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add the PDF file
          git add readme.pdf
          
          # Try to commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Generate PDF from readme.md"
            git push
          fi
