name: Convert README to PDF

on:
  push:
    branches: [ main, master ]
    paths:
      - 'readme.md'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the workflow with debug logging'
        required: false
        default: false
        type: boolean

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic

      - name: Convert README to PDF
        run: |
          echo "Converting readme.md to PDF"
          pandoc readme.md \
            -o readme.pdf \
            --pdf-engine=xelatex \
            -V geometry:margin=1in \
            -V documentclass=article \
            -V colorlinks=true \
            -V urlcolor=blue \
            --toc
          
          # Debug: Check if PDF was created
          if [ -f "readme.pdf" ]; then
            echo "✅ Successfully created readme.pdf"
          else
            echo "❌ Failed to create readme.pdf"
          fi

      - name: Commit PDF file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add the PDF file
          git add readme.pdf
          
          # Try to commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Generate PDF from readme.md"
            git push
          fi
