name: Convert README to PDF

on:
  push:
    branches: [ main, master ]
    paths:
      - 'readme.md'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the workflow with debug logging'
        required: false
        default: false
        type: boolean

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic fonts-liberation fonts-dejavu

      - name: Create styles directory
        run: mkdir -p styles

      - name: Create GitHub-style CSS file
        run: |
          cat > styles/github-style.css << 'EOF'
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
            line-height: 1.6;
            color: #24292e;
            max-width: 980px;
            margin: 0 auto;
            padding: 45px;
          }

          h1, h2, h3, h4, h5, h6 {
            margin-top: 24px;
            margin-bottom: 16px;
            font-weight: 600;
            line-height: 1.25;
            border: none;
          }

          h1:before, h2:before, h3:before, h4:before, h5:before, h6:before {
            content: none;
          }

          h1 {
            font-size: 2em;
            padding-bottom: 0.3em;
            border-bottom: 1px solid #eaecef;
          }

          h2 {
            font-size: 1.5em;
            padding-bottom: 0.3em;
            border-bottom: 1px solid #eaecef;
          }

          h3 {
            font-size: 1.25em;
            font-weight: 600;
            border-bottom: none;
          }

          p {
            margin-top: 0;
            margin-bottom: 16px;
          }

          a {
            color: #0366d6;
            text-decoration: none;
          }

          a:hover {
            text-decoration: underline;
          }

          code {
            font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace;
            background-color: rgba(27, 31, 35, 0.05);
            padding: 3px 5px;
            border-radius: 3px;
            font-size: 85%;
          }

          ul, ol {
            padding-left: 2em;
            margin-top: 0;
            margin-bottom: 16px;
          }

          li {
            margin-top: 0.25em;
            display: list-item !important;
          }

          li p {
            margin-top: 16px;
            display: block !important;
          }

          li + li {
            margin-top: 0.25em;
          }

          ul ul, ol ol, ul ol, ol ul {
            margin-top: 0;
            margin-bottom: 0;
          }

          blockquote {
            margin: 0;
            padding: 0 1em;
            color: #6a737d;
            border-left: 0.25em solid #dfe2e5;
          }

          table {
            display: block;
            width: 100%;
            overflow: auto;
            border-spacing: 0;
            border-collapse: collapse;
            margin-top: 0;
            margin-bottom: 16px;
          }

          table tr {
            background-color: #fff;
            border-top: 1px solid #c6cbd1;
          }

          table tr:nth-child(2n) {
            background-color: #f6f8fa;
          }

          table th, table td {
            padding: 6px 13px;
            border: 1px solid #dfe2e5;
          }

          table th {
            font-weight: 600;
          }

          strong {
            font-weight: 600;
          }

          /* Resume specific styles */
          em {
            font-style: italic;
            font-size: 1em;
            color: #586069;
            display: block;
            margin-bottom: 1em;
          }

          /* Add GitHub-like styling for bullet lists */
          ul li::marker {
            color: #24292e;
          }

          /* Skills section - make skill keywords stand out */
          #skills + ul strong {
            color: #24292e;
          }

          /* Experience section formatting */
          h1 + ul, h2 + ul, h3 + ul {
            margin-top: 8px;
          }
          EOF

      - name: Create GitHub-style LaTeX template
        run: |
          cat > styles/github-template.tex << 'EOF'
          \documentclass[11pt]{article}
          \usepackage{amssymb,amsmath}
          \usepackage{ifxetex,ifluatex}
          \usepackage{fixltx2e}
          \usepackage{enumerate}
          \usepackage[shortlabels]{enumitem}

          % GitHub-like list settings
          \setlist{nosep}
          \setlist[itemize]{leftmargin=*, itemsep=4pt, parsep=0pt}
          \setlist[enumerate]{leftmargin=*, itemsep=4pt, parsep=0pt}

          \usepackage{lmodern}
          \usepackage{xcolor}
          \usepackage{fontspec}

          % Colors matching GitHub
          \definecolor{github-black}{HTML}{24292E}
          \definecolor{github-blue}{HTML}{0366D6}
          \definecolor{github-gray}{HTML}{586069}

          % Remove section numbering
          \usepackage{titlesec}
          \titleformat{\section}{\Large\bfseries\color{github-black}}{}{0em}{}[\vspace{-0.3em}\rule{\textwidth}{0.1pt}\vspace{0.5em}]
          \titleformat{\subsection}{\large\bfseries\color{github-black}}{}{0em}{}[\vspace{-0.3em}\rule{\textwidth}{0.1pt}\vspace{0.5em}]
          \titleformat{\subsubsection}{\bfseries\color{github-black}}{}{0em}{}

          \usepackage[setpagesize=false, unicode=false, xetex]{hyperref}
          \hypersetup{breaklinks=true,
                      bookmarks=true,
                      colorlinks=true,
                      urlcolor=github-blue,
                      linkcolor=github-blue,
                      pdfborder={0 0 0}}
          \urlstyle{same}

          % Better handling of hyphens in lists
          \def\tightlist{\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

          % GitHub-like fonts
          \setmainfont{DejaVu Sans}
          \setmonofont{DejaVu Sans Mono}

          % Better handling of page margins for resumes
          \usepackage[margin=1in, top=0.75in]{geometry}

          % Improve spacing for description-like elements
          \newenvironment{jobdescription}{
            \begin{list}{$\bullet$}{
              \setlength{\leftmargin}{1em}
              \setlength{\itemsep}{0.25em}
              \setlength{\parsep}{0pt}
              \setlength{\topsep}{0pt}
            }
          }{
            \end{list}
          }

          % Custom command for job dates
          \newcommand{\jobdate}[1]{{\itshape\color{github-gray}#1\par\vspace{0.5em}}}

          \begin{document}
          \color{github-black}

          $body$

          \end{document}
          EOF

      - name: Preprocess README for better compatibility
        run: |
          # Create a preprocessed copy of the markdown with improved list formatting
          cp readme.md readme_processed.md
          
          # Ensure proper spacing for list items (both * and - markers)
          sed -i 's/^- /\n- /g' readme_processed.md
          sed -i 's/^\* /\n* /g' readme_processed.md
          
          # Add blank lines before headings for better separation
          sed -i 's/^##/\n##/g' readme_processed.md
          sed -i 's/^###/\n###/g' readme_processed.md

      - name: Convert README to PDF
        run: |
          echo "Converting readme.md to PDF with GitHub styling"
          
          pandoc readme_processed.md \
            -o readme.pdf \
            --pdf-engine=xelatex \
            -V papersize=letter \
            --template=styles/github-template.tex \
            --css=styles/github-style.css \
            --highlight-style=tango
          
          # Clean up
          rm readme_processed.md
          
          # Debug: Check if PDF was created
          if [ -f "readme.pdf" ]; then
            echo "✅ Successfully created readme.pdf"
            ls -la readme.pdf
          else
            echo "❌ Failed to create readme.pdf"
          fi

      - name: Commit PDF file and styles
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add the PDF file and style files
          git add readme.pdf styles/
          
          # Try to commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Generate GitHub-styled PDF from readme.md"
            git push
          fi
