name: Convert README to PDF

on:
  push:
    branches: [ main, master ]
    paths:
      - 'readme.md'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the workflow with debug logging'
        required: false
        default: false
        type: boolean

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic fonts-liberation fonts-dejavu

      - name: Create minimal template
        run: |
          # Create a very simple template to debug issues
          cat > minimal-template.tex << 'EOF'
          \documentclass[11pt]{article}
          \usepackage{amssymb,amsmath}
          \usepackage{fixltx2e}
          \usepackage{enumitem}
          \usepackage{lmodern}
          \usepackage{xcolor}
          \usepackage{fontspec}
          \usepackage{titlesec}
          \usepackage[margin=1in]{geometry}

          % Remove section numbering
          \titleformat{\section}{\Large\bfseries}{}{0em}{}
          \titleformat{\subsection}{\large\bfseries}{}{0em}{}
          \titleformat{\subsubsection}{\bfseries}{}{0em}{}

          % Better lists
          \setlist[itemize]{leftmargin=*}

          % Default font
          \setmainfont{DejaVu Sans}

          \begin{document}

          $body$

          \end{document}
          EOF

      - name: Preprocess README
        run: |
          cp readme.md readme_processed.md
          sed -i 's/^- /\n- /g' readme_processed.md
          sed -i 's/^\* /\n* /g' readme_processed.md

      - name: Convert with minimal template
        run: |
          echo "Converting with minimal template for debugging"
          
          pandoc readme_processed.md \
            -o readme.pdf \
            --pdf-engine=xelatex \
            -V papersize=letter \
            --template=minimal-template.tex
          
          if [ -f "readme.pdf" ]; then
            echo "✅ Successfully created readme.pdf"
            ls -la readme.pdf
          else
            echo "❌ Failed to create readme.pdf"
          fi

      - name: Commit PDF file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add the PDF file
          git add readme.pdf
          
          # Try to commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Generate PDF from readme.md (minimal template)"
            git push
          fi
